### ISSUE TITLE
DNS HTTPS

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TinyPen#8]
tiny.t-pen.org

dev.tiny.t-pen.org

**Comment by cubap** [comment]
@thehabes tiny.t-pen.org isn't up right now?

**Comment by thehabes** [comment]
@cubap It is there and ready.  Prod DNS is not behaving.  We might be getting U-turned.

I am getting proxy errors from prod.  dev is doing it correctly.  Both using http:// and I am on VPN FWIW.  See screenshots below.

![image 1](https://github.com/CenterForDigitalHumanities/TinyPen/assets/3287006/acc6dd3a-1549-4b8f-bf27-bfc871fc0025)

![image (3)](https://github.com/CenterForDigitalHumanities/TinyPen/assets/3287006/8e4f600f-8eb2-4323-bd0d-b5daa04d2a32)

**Comment by cubap** [comment]
```
[Fri Mar  8 17:01:52 CST 2024] Your cert is in: /root/.acme.sh/tiny.t-pen.org_ecc/tiny.t-pen.org.cer
[Fri Mar  8 17:01:52 CST 2024] Your cert key is in: /root/.acme.sh/tiny.t-pen.org_ecc/tiny.t-pen.org.key
[Fri Mar  8 17:01:52 CST 2024] The intermediate CA cert is in: /root/.acme.sh/tiny.t-pen.org_ecc/ca.cer
[Fri Mar  8 17:01:52 CST 2024] And the full chain certs is there: /root/.acme.sh/tiny.t-pen.org_ecc/fullchain.cer
```

**Comment by cubap** [comment]
```
[Mon Mar 11 12:22:41 CDT 2024] Your cert is in: /root/.acme.sh/dev.tiny.t-pen.org_ecc/dev.tiny.t-pen.org.cer
[Mon Mar 11 12:22:41 CDT 2024] Your cert key is in: /root/.acme.sh/dev.tiny.t-pen.org_ecc/dev.tiny.t-pen.org.key
[Mon Mar 11 12:22:41 CDT 2024] The intermediate CA cert is in: /root/.acme.sh/dev.tiny.t-pen.org_ecc/ca.cer
[Mon Mar 11 12:22:41 CDT 2024] And the full chain certs is there: /root/.acme.sh/dev.tiny.t-pen.org_ecc/fullchain.cer
```

**Comment by cubap** [comment]
dev is working. prod is catching a /TPEN rewrite rule somewhere and breaking

**Comment by cubap** [comment]
Secured done on both.
SG..users-3 had made a local copy of ssl.conf somehow and was editing the wrong one.
